### ISSUE TITLE
Einzelne Geräte ausschliessen

### ISSUE THREAD

**Issue by SpezialAgent** [ciddi89/ioBroker_device_watchdog#1]
Kann man einzelne Geräte aus der Überwachung ausschliessen? Es könnte ja ein Array abgefragt werden.

**Comment by ciddi89** [comment]
Habe eine const hinzugefügt mit den Namen "myArrFilter" Hier können devices angegeben werden die ausgeschlossen werden soll.

**Comment by SpezialAgent** [comment]
Super, das ging ja wahnsinnig schnell. Vielen Dank!
